#!/bin/bash

# Log Locations Guide for my.neonpanel.com OAuth Server
# This script provides common log locations to check

echo "=== Where to Find OAuth Logs on my.neonpanel.com ==="
echo ""
echo "Since my.neonpanel.com appears to be a Laravel/Symfony application"
echo "(based on the error message we saw earlier), here are common log locations:"
echo ""

echo "1. SSH into my.neonpanel.com server:"
echo "   ssh user@my.neonpanel.com"
echo "   # or if you have a specific host:"
echo "   ssh your-username@your-server-ip"
echo ""

echo "2. Common Laravel/PHP log locations:"
echo ""
echo "   A. Laravel application logs:"
echo "      tail -f storage/logs/laravel.log"
echo "      tail -f storage/logs/laravel-$(date +%Y-%m-%d).log"
echo ""

echo "   B. Nginx access/error logs:"
echo "      tail -f /var/log/nginx/access.log"
echo "      tail -f /var/log/nginx/error.log"
echo "      tail -f /var/log/nginx/my.neonpanel.com-access.log"
echo "      tail -f /var/log/nginx/my.neonpanel.com-error.log"
echo ""

echo "   C. Apache logs (if using Apache):"
echo "      tail -f /var/log/apache2/access.log"
echo "      tail -f /var/log/apache2/error.log"
echo ""

echo "   D. PHP-FPM logs:"
echo "      tail -f /var/log/php-fpm/error.log"
echo "      tail -f /var/log/php8.x-fpm.log"
echo ""

echo "   E. System logs:"
echo "      tail -f /var/log/syslog"
echo "      journalctl -u nginx -f"
echo "      journalctl -u php-fpm -f"
echo ""

echo "3. Filter for OAuth-specific logs:"
echo ""
echo "   # Watch for token exchange requests"
echo "   tail -f storage/logs/laravel.log | grep -i 'oauth2/token'"
echo ""
echo "   # Watch for all OAuth requests"
echo "   tail -f storage/logs/laravel.log | grep -i 'oauth'"
echo ""
echo "   # Watch nginx access log for POST to token endpoint"
echo "   tail -f /var/log/nginx/access.log | grep 'POST.*oauth2/token'"
echo ""

echo "4. Search recent logs for errors:"
echo ""
echo "   # Last 100 lines with OAuth mentions"
echo "   grep -i 'oauth' storage/logs/laravel.log | tail -100"
echo ""
echo "   # Search for today's token requests"
echo "   grep 'oauth2/token' storage/logs/laravel-$(date +%Y-%m-%d).log"
echo ""
echo "   # Find recent 500 errors"
echo "   grep -i 'error\|exception\|500' storage/logs/laravel.log | tail -50"
echo ""

echo "5. Quick health check (from MCP server):"
echo ""
echo "   # Test token endpoint is reachable"
echo "   curl -X POST https://my.neonpanel.com/oauth2/token \\"
echo "     -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "     -d 'grant_type=authorization_code' \\"
echo "     -d 'code=test' 2>&1 | head -20"
echo ""

echo "=== What to Look For ==="
echo ""
echo "When you try connecting in ChatGPT, watch the logs for:"
echo ""
echo "  ✅ POST request to /oauth2/token from ChatGPT"
echo "  ✅ Parameters: grant_type, code, redirect_uri, client_id, code_verifier"
echo "  ✅ Response status: 200, 400, 401, or 500"
echo ""
echo "Common errors:"
echo "  ❌ 'invalid_grant' - code expired, wrong redirect_uri, or code already used"
echo "  ❌ 'invalid_client' - client_id/client_secret wrong"
echo "  ❌ 'invalid_request' - missing required parameters"
echo "  ❌ PKCE verification failed"
echo "  ❌ redirect_uri mismatch"
echo ""

echo "=== If You Don't Have SSH Access ==="
echo ""
echo "If you don't have direct SSH access to my.neonpanel.com:"
echo ""
echo "1. Check if there's a web-based log viewer in the admin panel"
echo "2. Ask the server administrator to check the logs"
echo "3. Look for application monitoring (e.g., Sentry, Datadog, CloudWatch)"
echo "4. Check if there's an API to retrieve logs"
echo ""

echo "=== Alternative: Test Token Exchange Locally ==="
echo ""
echo "You can test the token exchange without ChatGPT to see if it works:"
echo ""
echo "1. Get an authorization code manually:"
echo "   - Visit: https://my.neonpanel.com/oauth2/authorize?..."
echo "   - Authorize and capture the code from redirect URL"
echo ""
echo "2. Exchange code for token with curl:"
echo "   curl -X POST https://my.neonpanel.com/oauth2/token \\"
echo "     -H 'Content-Type: application/x-www-form-urlencoded' \\"
echo "     -d 'grant_type=authorization_code' \\"
echo "     -d 'code=YOUR_CODE_HERE' \\"
echo "     -d 'client_id=YOUR_CLIENT_ID' \\"
echo "     -d 'redirect_uri=YOUR_REDIRECT_URI' \\"
echo "     -d 'code_verifier=YOUR_VERIFIER' \\"
echo "     -v"
echo ""

echo "=== Next Steps ==="
echo ""
echo "1. SSH into my.neonpanel.com"
echo "2. Start watching the logs (use commands above)"
echo "3. Try connecting in ChatGPT"
echo "4. Share any errors you see in the logs"
echo ""
echo "The logs will tell us exactly what's failing! 🔍"
