import type { ToolRegistry } from '../types';
import { registerSupplyChainInspectInventorySkuSnapshotTool } from './tools/supply_chain/inspect_inventory_sku_snapshot/register';
import { registerSupplyChainAnalyzeSalesVelocityTool } from './tools/supply_chain/analyze_sales_velocity/register';
import { registerSupplyChainListProductLogisticsParametersTool } from './tools/supply_chain/list_product_logistics_parameters/register';
import { registerSupplyChainListFbaReplenishmentCandidatesTool } from './tools/supply_chain/list_fba_replenishment_candidates/register';
import { registerSupplyChainListPoPlacementCandidatesTool } from './tools/supply_chain/list_po_placement_candidates/register';
import { registerSupplyChainListStockReplenishmentRiskItemsTool } from './tools/supply_chain/list_stock_replenishment_risk_items/register';
import { registerShipmentArrivalOracle } from './tools/supply_chain/shipment_arrival_oracle/register';
import { registerForecastingListLatestSalesForecastTool } from './tools/forecasting/list_latest_sales_forecast/register';
import { registerForecastingCompareSalesForecastScenariosTool } from './tools/forecasting/compare_sales_forecast_scenarios/register';
import { registerForecastingWriteSalesForecastTool } from './tools/forecasting/write_sales_forecast/register';
import { registerForecastingGenerateSalesForecastTool } from './tools/forecasting/generate_sales_forecast/register';
import { registerBrandAnalyticsGetCompetitiveLandscapeTool } from './tools/brand_analytics/get_competitive_landscape/register';
import { registerBrandAnalyticsGetKeywordFunnelMetricsTool } from './tools/brand_analytics/get_keyword_funnel_metrics/register';
import { registerBrandAnalyticsGetSearchTermMomentumTool } from './tools/brand_analytics/get_search_term_momentum/register';
import { registerBrandAnalyticsAnalyzeSearchQueryPerformanceTool } from './tools/brand_analytics/analyze_search_query_performance/register';
import { registerBrandAnalyticsAnalyzeSearchCatalogPerformanceTool } from './tools/brand_analytics/analyze_search_catalog_performance/register';
import { registerCogsAnalyzeFifoCogsTool } from './tools/cogs/analyze_fifo_cogs/register';
import { registerCogsExportUnitCostsTool } from './tools/cogs/export_unit_costs/register';
import { registerInventoryValuationAnalyzeInventoryValueTool } from './tools/inventory_valuation/analyze_inventory_value/register';
import { registerSearchNeonpanelProjectUrl } from './tools/projects/search_neonpanel_project_url/register';
import { registerAdvertisingAnalyzeSearchTermsTool } from './tools/amazon_advertising/analyze_search_terms/register';
import { registerAdvertisingAnalyzeCampaignPerformanceTool } from './tools/amazon_advertising/analyze_campaign_performance/register';
import { registerFinancialsAnalyzeGeneralLedgerTool } from './tools/financials/analyze_general_ledger/register';
import { registerFinancialsListAccountTransactionsTool } from './tools/financials/list_account_transactions/register';

export function registerAthenaTools(registry: ToolRegistry) {
  // Keep this list small and explicit to control ordering in tools/list.
  registerForecastingListLatestSalesForecastTool(registry);
  registerForecastingCompareSalesForecastScenariosTool(registry);
  registerForecastingWriteSalesForecastTool(registry);
  registerForecastingGenerateSalesForecastTool(registry);
  registerSupplyChainListFbaReplenishmentCandidatesTool(registry);
  registerSupplyChainListPoPlacementCandidatesTool(registry);
  registerSupplyChainListStockReplenishmentRiskItemsTool(registry);
  registerSupplyChainAnalyzeSalesVelocityTool(registry);
  registerShipmentArrivalOracle(registry);
  registerSupplyChainInspectInventorySkuSnapshotTool(registry);
  registerSupplyChainListProductLogisticsParametersTool(registry);
  registerBrandAnalyticsGetCompetitiveLandscapeTool(registry);
  registerBrandAnalyticsGetKeywordFunnelMetricsTool(registry);
  registerBrandAnalyticsGetSearchTermMomentumTool(registry);
  registerBrandAnalyticsAnalyzeSearchQueryPerformanceTool(registry);
  registerBrandAnalyticsAnalyzeSearchCatalogPerformanceTool(registry);
  registerCogsAnalyzeFifoCogsTool(registry);
  registerCogsExportUnitCostsTool(registry);
  registerInventoryValuationAnalyzeInventoryValueTool(registry);
  registerAdvertisingAnalyzeSearchTermsTool(registry);
  registerAdvertisingAnalyzeCampaignPerformanceTool(registry);
  registerFinancialsAnalyzeGeneralLedgerTool(registry);
  registerFinancialsListAccountTransactionsTool(registry);
  registerSearchNeonpanelProjectUrl(registry);
}
